workflows:
  android:
    name: Android debug workflow
    scripts:
     - name: Set Android SDK location
        script: |
           echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"          
      - name: Build Android
        script: 
           ./gradlew assembleDebug          
    artifacts: |
      - app/build/outputs/apk/debug/app-debug.apk

  flutter-ios-simulator:
    name: Flutter iOS Simulator
    environment:
      flutter: 3.27.3
      xcode: latest
    scripts:
      - flutter build ios --simulator --flavor staging  # --flavor is optional
        artifacts:
      - build/ios/iphonesimulator/Runner.app
